{% set name = "sphinx-math-dollar" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 03427240f21fdf23c7b8415289aa1a0e307ac32c198e02f840c59a4b1b0d950c

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - sphinx

test:
  requires:
    - python {{ python_min }}
  imports:
    - sphinx_math_dollar

about:
  home: https://www.sympy.org/sphinx-math-dollar/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: sphinx-math-dollar is a Sphinx extension to let you write LaTeX math using $$.
  doc_url: https://www.sympy.org/sphinx-math-dollar/
  dev_url: https://github.com/sympy/sphinx-math-dollar

extra:
  recipe-maintainers:
    - asmeurer
