{% set name = "sphinx-math-dollar" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9e18e9ed398c9e556eab74eef9333f7a0b39a8c176988b61aedecd085336a20f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - sphinx

test:
  requires:
    - python {{ python_min }}
  imports:
    - sphinx_math_dollar

about:
  home: https://www.sympy.org/sphinx-math-dollar/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: sphinx-math-dollar is a Sphinx extension to let you write LaTeX math using $$.
  doc_url: https://www.sympy.org/sphinx-math-dollar/
  dev_url: https://github.com/sympy/sphinx-math-dollar

extra:
  recipe-maintainers:
    - asmeurer
