{% set name = "sphinx-math-dollar" %}
{% set version = "1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c3030c7881dec4ad3d74596200708ba79a94baf32569cbcf45f7090aa8126ab2

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - sphinx

test:
  imports:
    - sphinx_math_dollar

about:
  home: https://www.sympy.org/sphinx-math-dollar/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'sphinx-math-dollar is a Sphinx extension to let you write LaTeX math using $$.'
  doc_url: https://www.sympy.org/sphinx-math-dollar/
  dev_url: https://github.com/sympy/sphinx-math-dollar

extra:
  recipe-maintainers:
    - asmeurer
