travis:
  secure:
    BINSTAR_TOKEN: PFq9SYIEqBgXTKgfMj438m5q3DBTDs+VqEFOsTYUE2H/wUQhfjQSX+dpmEV13TJnJKF1Vtw4H4A8CGe/MB76CLX1vy8wzW8BvmI3JxYyX0e69zmTunM7WoP/yfJ7bTpA+nDEdpd08gtMCneIYXqtFzjfnLcHO+4C+j9w282LnJzCHxKbmTe+mbz91R6k20f+/ArCAXTSSMpPNSvYduBOhqmV77iHts8IwtOB6TEPBSjeqkEvxZcqNK5+YeYdtEzKaSdDqsliSUjuyPuoEhMiDUOHTFtCiuXfgGTt34dn1QzhqGEMvi7fK9fqdVf8TsraZcCjW0LJIFfgQgb7oXs+vxaQhP3RzEVxYNpAe8tmI0uT8IzpOUskkDPpAwaVDo6pQK03H5ktXSdZvCCt+Q3KaUywY86cwUowm8mrRt4d1/0zBrDuBpUZS4QwNMFAx27nVqXDmlARligME9bGRHm03w9lxAloaNW5c3fLN5aEZcrNn18Wu5ukwtcheHpLCVdM6Vt8N8kJQ5b3QL7U/FA4x8sWhVzz1ifa+JtZPupaW5A4ICKJBZYSlkMAPQ4fL8RxUHyLOFEO4b2TYaiZAWRLaNxfVDFetB6DbQ4NRZYQXV0ygLGPRXx+dFuBIKaj+EkAEYhgeD3oxe4QwpNs8Mzbs+0+ejqmEY+Rrox4eztAVho=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
